[package]
name = "origamic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^4.5.1", features = ["derive"] }
colored = "2.1.0"
logos = "0.14.0"
rug = "1.24.0"
serde = "1.0.197"
thiserror = "1.0.57"
unicode-segmentation = "1.11.0"
